version: "3.8"
networks:
  mojaloop-net:
    name: mojaloop-net


services:
  mifosCoreConnector:
    image: mojaloop/mifos-core-connector:latest
    build:
      context: ../..
    networks:
      - mojaloop-net
    environment:
      - FINERACT_TENANT_ID=default
      - FINERACT_AUTH_MODE=basic
      - FINERACT_USERNAME=mifos
      - FINERACT_PASSWORD=password
      - FINERACT_BANK_ID=0720
      - FINERACT_ACCOUNT_PREFIX=000289
      - FINERACT_BANK_COUNTRY_CODE=UG
      - FINERACT_CHECK_DIGITS=68
      - FINERACT_LOCALE=en
      - SDK_SERVER_HOST=mifosCoreConnector
      - SDK_SERVER_PORT=3003
      - DFSP_SERVER_HOST=mifosCoreConnector
      - DFSP_SERVER_PORT=3004
      - FINERACT_BASE_URL=https://demo.mifos.io/fineract-provider/api/v1
      - SDK_BASE_URL=http:/0.0.0.0:4010
    ports:
      - "3003:3003"
      - "3004:3004"